#pragma once

#include "__windows_shim_msvcrt.h"

#include <stdint.h>

#include <errno.h>

#define ERROR_SUCCESS 0
#define ERROR_FILE_NOT_FOUND ENOENT
#define ERROR_ACCESS_DENIED EPERM
#define ERROR_INVALID_HANDLE EBADF
#define ERROR_NOT_ENOUGH_MEMORY ENOMEM
#define ERROR_NOT_SUPPORTED ENOTSUP
#define ERROR_INVALID_PARAMETER EINVAL
#define ERROR_NEGATIVE_SEEK ESPIPE
#define ERROR_DISK_FULL ENOSPC
#define ERROR_ALREADY_EXISTS EEXIST
#define ERROR_INSUFFICIENT_BUFFER ENOBUFS
#define ERROR_BAD_FORMAT 1000 // No such error codes under Linux
#define ERROR_NO_MORE_FILES 1001
#define ERROR_HANDLE_EOF 1002
#define ERROR_CAN_NOT_COMPLETE 1003
#define ERROR_FILE_CORRUPT 1004
#define ERROR_BUFFER_OVERFLOW 1005
#define ERROR_INVALID_DATA 1006
#define ERROR_NO_UNICODE_TRANSLATION 1007

#define INVALID_SET_FILE_POINTER 9999 // Unknown if correct
